title: Skolmat
views:
  - title: Skolmat
    path: skolmat
    cards:

      - type: custom:skolmat-card
        entity: sensor.skolmaten_se_skutehagen
        
        menu_type: today
        header: full
      - type: custom:skolmat-card
        entity: sensor.skolmaten_se_skutehagen
        menu_type: week
        header: full

      # show_dates
      - type: custom:skolmat-card
        entity: sensor.skolmaten_se_skutehagen
        menu_type: week
        header: full
        show_dates: True

      # rolling-week (should default to 5 days)
      - type: custom:skolmat-card
        entity: sensor.skolmaten_se_skutehagen
        menu_type: rolling-week
        header: full
      
      # max_display_days (rolling week, 10 days)
      - type: custom:skolmat-card
        entity: sensor.skolmaten_se_skutehagen
        menu_type: rolling-week
        header: full
        rolling_week_max_days: 10

      - type: custom:skolmat-card
        entity: skolmat.foodit_se_backaskolan
        menu_type: today
        header: full
      - type: custom:skolmat-card
        entity: skolmat.foodit_se_backaskolan
        menu_type: week
        header: full

      - type: custom:skolmat-card
        entity: skolmat.mpi_mashie_com_kyrkebyskolan
        menu_type: today
        header: full
      - type: custom:skolmat-card
        entity: skolmat.mpi_mashie_com_kyrkebyskolan
        menu_type: week
        header: full

      - type: custom:skolmat-card
        entity: skolmat.mpi_mashie_com_scheeleskolan
        menu_type: today
        header: full
      - type: custom:skolmat-card
        entity: skolmat.mpi_mashie_com_scheeleskolan
        menu_type: week
        header: full

      - type: custom:skolmat-card
        entity: skolmat.skolmaten_se_stadastadsskogen_skola
        menu_type: today
        header: full
      - type: custom:skolmat-card
        entity: skolmat.skolmaten_se_stadastadsskogen_skola
        menu_type: week
        header: full

      - type: custom:skolmat-card
        entity: skolmat.mateo_se_kavlinge_utbildning
        menu_type: today
        header: full
      - type: custom:skolmat-card
        entity: skolmat.mateo_se_kavlinge_utbildning
        menu_type: week
        header: full


      - type: custom:skolmat-card
        entity: skolmat.menu_matildaplatform_com_dalajars_forskola
        menu_type: week
        header: full



